### ISSUE TITLE
android APIs 24-26 not supported and giving this error after giving permissions

### ISSUE THREAD

**Issue by alzubitariq** [melihercan/WebRTCme#1]
Java.Lang.NoSuchMethodError: 'no non-static method "Landroid/media/AudioManager;.getMicrophones()Ljava/util/List;"'

**Comment by alzubitariq** [comment]
to handle that backwards compatible , I think you have to check WebRTCme project => Android =>MediaStream class and replace
this 
 
var id = audioManager.Microphones[0].Id;
 
with this 
 int id = 0;
 if (Build.VERSION.SdkInt >= BuildVersionCodes.P)
{
    id = audioManager.Microphones[0].Id;
}
 else
 {
       AudioDeviceInfo[] deviceInfo = audioManager.GetDevices(GetDevicesTargets.Inputs);
       id = deviceInfo[0].Id;
 }

**Comment by melihercan** [comment]
Thanks for the tip, I will add it to the code.
