### ISSUE TITLE
Java.Lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Vuyiswamb** [melihercan/WebRTCme#10]
Good Day 
i get this error while trying to run a demo 

**Java.Lang.NoSuchMethodError
  Message=no static method "Lorg/webrtc/EglBase;.create()Lorg/webrtc/EglBase;"**

on this line 

`var webRtcMiddleware = CrossWebRtcMiddlewareXamarin.Current;`

Thanks

**Comment by melihercan** [comment]
If you are having trouble with this in the updated version, kindly reopen.
