### ISSUE TITLE
WebRTC Video Call in Xamarin with Any Signaling Server

### ISSUE THREAD

**Issue by mail2mhossain** [melihercan/WebRTCme#16]
I am trying to user only WebRTC part in my Xamarin project but failed to figure out how to initialize. I have attached a sequence diagram. In this way I am trying. Would you please help me to use your webRTC Api in this way.

![WebRTC_Video_Call](https://user-images.githubusercontent.com/6905164/161474607-1cceed80-80f9-4abd-a2d6-ec5e288ffd8d.png)

Plant UML Code:
@startuml WebRTC
	title       WebRTC Video Call Sequence

	Bob -> SignalingServer: Register
	Alice -> SignalingServer: Register
	group Call
		Bob -> Bob: InitPeerConnection()
		group InitPeerConnection
			Bob -> Bob: CreatePeerConnection()
			Bob -> Bob: ReceiveVideoTrack()
		end
		Bob -> Bob: CreateVideoCaptureDevice()
		Bob -> Bob: CreateAudioCaptureDevice()
		Bob -> Bob: AddVideoTransceiver()
		Bob -> Bob: AddAudioTransceiver()
		Bob -> Bob: CreateOffer()
		Bob -> Bob: SetLocalDescription()
		Bob -> SignalingServer: SendOfferSdp
		SignalingServer -> Alice: SendOfferSdp
		Alice -> Alice: InitPeerConnection()
		group InitPeerConnection
			Alice -> Alice: CreatePeerConnection()
			Alice -> Alice: ReceiveVideoTrack()
		end
		Alice -> Alice: CreateVideoCaptureDevice()
		Alice -> Alice: CreateAudioCaptureDevice()
		Alice -> Alice: AddVideoTransceiver()
		Alice -> Alice: AddAudioTransceiver()
		Alice -> Alice: SetRemoteDescription()
		Alice -> Alice: CreateAnswer()
		Alice -> SignalingServer: SendAnswerSdp
		SignalingServer -> Bob: SendAnswerSdp
		Bob -> Bob: SetRemoteDescription()

		Bob -> SignalingServer: SendIceCandidate()
		SignalingServer -> Alice: SendIceCandidate()
		Alice -> Alice: AddIceCandidate()

		Alice -> SignalingServer: SendIceCandidate()
		SignalingServer -> Bob: SendIceCandidate()
		Bob -> Bob: AddIceCandidate()
		Bob <-> Alice: P2PConnection
	end
@enduml

**Comment by melihercan** [comment]
Hi, sorry currently I have no time to spend on this request. 
Please check the Demo application which runs on Blazor, Android and iOS platforms. I hope you can find the answers there.

**Comment by melihercan** [comment]
You can create your own connection library using the current ones as a template.

**Comment by melihercan** [comment]
And middleware as well...
