### ISSUE TITLE
Middleware Hangup function

### ISSUE THREAD

**Issue by Vuyiswamb** [melihercan/WebRTCme#18]
The Demo example has a hangup function but the the nuget does not have that function , when is the latest version will be released on the nuget, or should i just compile the example projects and use the middleware ?

**Comment by Vuyiswamb** [comment]
Thank you very much .

**Comment by melihercan** [comment]
> The Demo example has a hangup function but the the nuget does not have that function , when is the latest version will be released on the nuget, or should i just compile the example projects and use the middleware ?

Please use the latest source code and compile it yourself for now. NuGet is pretty old and I am not yet to the level I want to release a new NuGet version.

Currently I am adding MAUI support (that will provide Windows and macOS desktop platforms in addition to mobile and WEB) and once completed, I will release a new version of the NuGet.
