### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by tgoeminne** [melihercan/WebRTCme#20]
Hi,

I was looking at this project, but I am kind of new to all this xamarin stuff. I have an app xamarin.forms project (android, ios) and want to use the webrtc for android and ios. The question is which package do I need to install and do I install it in App, or also in android and ios? I see in the demo it only uses the middleware one? Also is there any reason it requires 5.+ xamarin, I only use 4.8.

greets

**Comment by melihercan** [comment]
Hi,

The nuget packages are really old and I wouldn't recommend to use them until they are updated (currently I don't know when due to my heavy workload). Best is to get source code and use them as libraries.
