### ISSUE TITLE
Blazor server demo not working

### ISSUE THREAD

**Issue by taylorjimbo** [melihercan/WebRTCme#25]
I tried out WebRTCme a long time ago, but didn't really need it for a project. 

I downloaded the latest code and can not get the Blazor server or wasm demo to build. 

I started a new Blazor server app and adding the packages:

- WebRTCme
- WebRTC.Bindings
- WebRTC.Bindings.Blazor
- WebRTC.MiddleWare.Blazor
- WebRTCme.SignallingServerProxy

included the following in the program.cs
`var webRtcMiddleware = CrossWebRtcMiddlewareBlazor.Current;  `                                                                          
`builder.Services.AddSingleton(serviceProvider => webRtcMiddleware);`

and the javascript in the layout.chtml:
`<script src="_content/WebRTCme.Bindings.Blazor/JsInterop.js"></script>`

I can't seem to get this working - System.InvalidOperationException: Cannot provide a value for property 'ConnectionParametersViewModel'

Here is a link to the project I created - [https://github.com/taylorjimbo/BlazorApp5](https://github.com/taylorjimbo/BlazorApp5)

Does anyone have a working sample project?

**Comment by melihercan** [comment]
The NuGets need updates.

Please use the code for now. I build and run SignalingServer and DemoApp.Blazor.Wasm and they are working.

Please note that currently only WASM is supported for Blazor, NOT server.

**Comment by mizadpanahdev** [comment]
Could you please upload both projects: SignalingServer and DemoApp.Blazor.Wasm

**Comment by melihercan** [comment]
I have updated the code. Please try again and reopen the issue if needed.

**Comment by melihercan** [comment]
closing for now
