### ISSUE TITLE
Does not build - many errors

### ISSUE THREAD

**Issue by juergenr** [melihercan/WebRTCme#26]
It is a great idea to have a common API including Blazor!
But it should build out of the box without fiddling around.
If there are some special build steps needed, a step-by-step tutorial to get the demo running would be very helpful.

Here are 2 screenshots from errors:
![image](https://user-images.githubusercontent.com/5941457/208194772-72dc539c-80f9-4272-822a-7ee452aea293.png)
![image](https://user-images.githubusercontent.com/5941457/208194845-01046525-46c2-4eee-b0d6-e9f1563d65e8.png)

It would be a pity and very disappointing, when the great idea fails to get more attention, by simply not getting the demo work.
Thanks!

**Comment by melihercan** [comment]
Hi, on my side both build and demo works.

It seems that iOS DLL(s) are missing in your case. To build iOS DLLs, you need to connect to a macOS machine.

In order to eliminate iOS build, you can do the following:
in https://github.com/melihercan/WebRTCme/blob/master/WebRTCme/WebRTCme.csproj
change: 
	<TargetFrameworks>netstandard2.0;netstandard2.1;net5.0;net6.0;MonoAndroid12.0;Xamarin.iOS10;net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
to: 
	<TargetFrameworks>netstandard2.0;netstandard2.1;net5.0;net6.0;MonoAndroid12.0;net6.0-android;net6.0-maccatalyst</TargetFrameworks>

**Comment by juergenr** [comment]
Thanks for your fast answer!
I removed Xamarin.iOS10 from WebRTCme.csproj and removed all Xamarin project from the solution.
I also changed all the hard coded IP addresses: 192.168.178.50 to my own.
Then I could build it and the WebRTCme.DemoApp.Blazor.Wasm project can be started.

But it doesn't work as expected:
The camera stream is shown. But screensharing, recording, file sharing, chat all do NOT work.
I get following error message: "An error occured during the connection. Here is the reported error message: The 'InvokeCoreAsync' method cannot be called if the connection is not active"

It would really appreciate it, if you could test the project on a fresh (virtual) machine with an fresh up to date Visual Studio 2022 (e.g. Version 17.4.3) and write a short QuickStart. 

For a person testing the project the first time, it really does not feel good, if you need several hours to get the demo to run. 
Especially when the project owner could fix the problems and write a QuickStart in pretty no time.

A QuickStart tutorial and an out-of-the-box working demo would be really helpful.
To improve the project further, most urgent would be a some documentation.

**Comment by melihercan** [comment]
The documentation is just one of many TODOs. But I have a lot of commercial tasks on my plate right now, and I just don't have time to devote to this project. I'm now working on my commercial tasks on a Saturday night:(
After the new year, I hope to begin making improvements to the project.

For the time being, only Blazor supports screen sharing, file sharing, and recording (NO support on mobile or desktop platforms).

**Comment by lrutl** [comment]
> But it doesn't work as expected: The camera stream is shown. But screensharing, recording, file sharing, chat all do NOT work. I get following error message: "An error occured during the connection. Here is the reported error message: The 'InvokeCoreAsync' method cannot be called if the connection is not active"

I was able to resolve this by following the instructions in cert/README.txt

**Comment by melihercan** [comment]
Resolved
