### ISSUE TITLE
Creating a RTCPeerConnection in Xamarin.Forms

### ISSUE THREAD

**Issue by siggi90** [melihercan/WebRTCme#3]
I've been looking at the samples and I can't find any usage of the low level objects/functions like RTCPeerConnection, my aim is to create a RTCPeerConnection and data channel to communicate like a simple chat, but the WebRTCme nuget only seems to have an IRTCPeerConnection interface., is this possible with this library? Also I'm intending to use this on Xamarin UWP and Xamarin.Mac, will this work?

**Comment by melihercan** [comment]
Not on the short term. Similar to Android and iOS, the desktop bindings shall be created for that.

Blazor NuGet will not run on Forms. Blazor is using JS Interop to access WebRTC functionality embedded into the browser.
Blazor is not that hard:) And WebRTCme is using the same API for Xamarin and Blazor. So the code from my first message will be OK for Blazor too, with a parameter addition to Window() call ==> Window(jsRuntime).

**Comment by siggi90** [comment]
I'm making a desktop application that requires WebRTC on macOS and UWP and it's being developed in Xamarin.Forms since its not possible to add Blazor code and nugets directly to Xamarin.Forms i will have to wait for the desktop bindings being implemented. I was very glad to find this library it seems to be the only cross platform WebRTC solution. I've been trying to build the source code from google and implementing my own bindings, but have not been successful, so i will definitely be watching for the desktop bindings in the future. Thanks for the help with the code and info.

**Comment by melihercan** [comment]
You are welcome. 

It is possible to run hybrid code (Blazor with Xamarin). Worth to check I believe.
https://docs.microsoft.com/en-us/mobile-blazor-bindings/

Another option will be running Blazor code as desktop using Elektron:
https://www.youtube.com/watch?v=6MjxgbmTAAM

.NET6 will support Blazor Desktop out of the box:
https://visualstudiomagazine.com/articles/2021/02/17/net-6-preview-1.aspx

**Comment by hossam14102010** [comment]
can this be used now for Maui Windows and MacCatalyst

**Comment by melihercan** [comment]
> can this be used now for Maui Windows and MacCatalyst

Currently, there is limited support for both.
The core library (WebRTCme) can be used on Windows and Mac. They both employ the [SipSorcery](https://github.com/sipsorcery-org/sipsorcery) library.  It was not the ideal solution I wanted, but this is how it is now.
No support yet on Middleware and DemoApp layers.
