### ISSUE TITLE
Stable Branch/Version?

### ISSUE THREAD

**Issue by plumis1993** [melihercan/WebRTCme#5]
Hey, i am unable to build with latest changes/refactoring. "Melih" branch is working great but your latest changes really enhanced your webrtc implementation 

One major issue is that Result.csproj cannot be loaded.

**Comment by melihercan** [comment]
HI there,

Sorry for the break. I have added the Result project to Externals now and this should sort out your build problem.
I am having a major refactoring especially on Middleware and Servers, so code breakings are possible.

**Comment by melihercan** [comment]
When the MediaSoup support is completed, I will tag the code and make a new NuGet releases.

**Comment by plumis1993** [comment]
Thank you very much! cant wait for the final release
