### ISSUE TITLE
Jitsi demo app?

### ISSUE THREAD

**Issue by GeorgeS2019** [melihercan/WebRTCme#7]
Can this be used as a Jitsi client?

**Comment by melihercan** [comment]
Not out of the box. Currently I am working on MediaSoup integration and maybe in the future I can add Jitsi support. 

I don't know the details of Jitsi client SDK currently, but you can add Jitsi layer to WebRRCme.Connection folder by taking MediaSoup as an example.  You will need to add Proxy only NOT Server. 
You will also see WebRTCme.Connection generic wrapper project. Add JitsiConnection as a service there to the ConnectionFactory and you will be good to go :)

**Comment by melihercan** [comment]
Closing
